spring:
  application:
    name: InfraStructure
  datasource:
    username: postgres
    password: 12as12as
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    jdbc:
      dialect: postgresql
  security:
    user:
      name: ali
      password: 12as12as
